package codegen

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateMainFileAndHelpers(t *testing.T) {
	const good = `//go:build macro

package p
`
	if err := ValidateMainFile(good); err != nil {
		t.Fatal(err)
	}
	if !IsMacroMainFile(good) {
		t.Fatal("IsMacroMainFile")
	}
	if IsGenFile("foo_macro_gen.go") != true || IsGenFile("foo.go") {
		t.Fatal("IsGenFile")
	}
	gen, err := GenConstraint("macro")
	if err != nil || gen != "!macro" {
		t.Fatalf("GenConstraint: %q %v", gen, err)
	}
	if err := ValidateMainFile("package p\n"); err == nil {
		t.Fatal("want error without build tag")
	}
	if err := ValidateMainFile(`//go:build ignore

package p
`); err == nil {
		t.Fatal("want error for ignore only")
	}
}

func TestWriteGenFile(t *testing.T) {
	dir := t.TempDir()
	mainPath := filepath.Join(dir, "demo.go")
	const src = `//go:build macro

package demo

import (
	"fmt"
	"os"

	"github.com/arcane-craft/go-macro/contrib/try"
)

func F() error {
	return fmt.Errorf("x")
}
`
	if err := os.WriteFile(mainPath, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, mainPath, src, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	// Drop try import to exercise filterUnusedImports.
	file.Imports = append(file.Imports, &ast.ImportSpec{
		Path: &ast.BasicLit{Kind: token.STRING, Value: `"github.com/arcane-craft/go-macro/contrib/try"`},
	})
	filterUnusedImports(file)
	if err := WriteGenFile(mainPath, "!macro", fset, file); err != nil {
		t.Fatal(err)
	}
	genPath := genPathFor(mainPath)
	data, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	for _, want := range []string{
		"// Code generated by go-macro",
		"//go:build !macro",
		"package demo",
		"//line demo.go:",
		"func F() error",
		`return fmt.Errorf("x")`,
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("gen missing %q\n%s", want, s)
		}
	}
	if strings.Contains(s, "contrib/try") {
		t.Fatalf("gen must drop unused try import:\n%s", s)
	}
}

func TestPrintFuncDeclNoBody(t *testing.T) {
	fset := token.NewFileSet()
	f, _ := parser.ParseFile(fset, "x.go", "package p\nfunc G() {}\n", 0)
	fn := f.Decls[0].(*ast.FuncDecl)
	fn.Body = nil
	var buf bytes.Buffer
	cfg := printerConfig()
	if err := printFuncDecl(&buf, fset, fn, "x.go", cfg); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), "G() {}") {
		t.Fatalf("got %q", buf.String())
	}
}

func printerConfig() *printer.Config {
	return &printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
}
