package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/arcane-craft/go-macro/internal/constraint"
)

const genSuffix = "_macro_gen.go"

// WriteGenFile writes expanded AST to foo_macro_gen.go with complemented build tag and //line directives.
func WriteGenFile(mainPath string, genConstraint string, fset *token.FileSet, file *ast.File) error {
	lineFile := filepath.Base(mainPath)
	out := &ast.File{
		Name:    file.Name,
		Imports: file.Imports,
		Decls:   file.Decls,
	}

	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	buf.WriteString("// Code generated by go-macro; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "//go:build %s\n\n", genConstraint)
	fmt.Fprintf(&buf, "package %s\n", out.Name.Name)
	filterUnusedImports(out)
	if len(out.Imports) > 0 {
		specs := make([]ast.Spec, len(out.Imports))
		for i, s := range out.Imports {
			specs[i] = s
		}
		buf.WriteString("\n")
		_ = cfg.Fprint(&buf, fset, &ast.GenDecl{Tok: token.IMPORT, Specs: specs})
		buf.WriteString("\n")
	}
	for _, decl := range out.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if d.Tok != token.TYPE {
				continue
			}
			if err := printTypeGenDecl(&buf, fset, d, lineFile, &cfg); err != nil {
				return err
			}
		case *ast.FuncDecl:
			if err := printFuncDecl(&buf, fset, d, lineFile, &cfg); err != nil {
				return err
			}
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format gen: %w", err)
	}
	return os.WriteFile(genPathFor(mainPath), formatted, 0o644)
}

func printTypeGenDecl(buf *bytes.Buffer, fset *token.FileSet, gen *ast.GenDecl, lineFile string, cfg *printer.Config) error {
	var sb bytes.Buffer
	if err := cfg.Fprint(&sb, fset, gen); err != nil {
		return err
	}
	buf.Write(sb.Bytes())
	if sb.Len() == 0 || sb.Bytes()[sb.Len()-1] != '\n' {
		buf.WriteByte('\n')
	}
	buf.WriteByte('\n')
	return nil
}

func printFuncDecl(buf *bytes.Buffer, fset *token.FileSet, fn *ast.FuncDecl, lineFile string, cfg *printer.Config) error {
	var sig bytes.Buffer
	if err := cfg.Fprint(&sig, fset, fn.Type); err != nil {
		return err
	}
	sigStr := strings.TrimPrefix(sig.String(), "func")
	fmt.Fprintf(buf, "func %s%s", fn.Name.Name, sigStr)
	if fn.Body == nil {
		buf.WriteString(" {}\n\n")
		return nil
	}
	buf.WriteString(" {\n")
	for _, stmt := range fn.Body.List {
		line := stmtLine(fset, stmt)
		fmt.Fprintf(buf, "//line %s:%d\n", lineFile, line)
		var sb bytes.Buffer
		if err := cfg.Fprint(&sb, fset, stmt); err != nil {
			return err
		}
		buf.Write(sb.Bytes())
		if sb.Len() == 0 || sb.Bytes()[sb.Len()-1] != '\n' {
			buf.WriteByte('\n')
		}
	}
	buf.WriteString("}\n\n")
	return nil
}

func stmtLine(fset *token.FileSet, stmt ast.Stmt) int {
	if line := lineFromPos(fset, stmt.Pos()); line > 0 {
		return line
	}
	if line := firstLineInTree(fset, stmt); line > 0 {
		return line
	}
	return 1
}

func lineFromPos(fset *token.FileSet, pos token.Pos) int {
	if !pos.IsValid() {
		return 0
	}
	line := fset.Position(pos).Line
	if line < 1 {
		return 0
	}
	return line
}

func firstLineInTree(fset *token.FileSet, root ast.Node) int {
	var line int
	ast.Inspect(root, func(n ast.Node) bool {
		if line > 0 {
			return false
		}
		if n == nil {
			return true
		}
		if l := lineFromPos(fset, n.Pos()); l > 0 {
			line = l
			return false
		}
		return true
	})
	return line
}

func genPathFor(mainPath string) string {
	dir := filepath.Dir(mainPath)
	base := filepath.Base(mainPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	return filepath.Join(dir, name+genSuffix)
}

// ValidateMainFile checks macro main file constraints.
func ValidateMainFile(src string) error {
	expr, ok := constraint.ExtractBuildConstraint(src)
	if !ok || strings.TrimSpace(expr) == "" {
		return fmt.Errorf("macro main file must include //go:build with macro tag (e.g. //go:build macro)")
	}
	onlyIgnore, err := constraint.HasOnlyIgnore(expr)
	if err != nil {
		return err
	}
	if onlyIgnore {
		return fmt.Errorf("macro main file must not use only //go:build ignore; use macro tag instead (see README)")
	}
	hasMacro, err := constraint.HasMacro(expr)
	if err != nil {
		return err
	}
	if !hasMacro {
		return fmt.Errorf("macro main file build constraint must include macro identifier; merge with existing tags manually (e.g. macro && linux)")
	}
	return nil
}

// GenConstraint derives !macro side from main file constraint.
func GenConstraint(mainExpr string) (string, error) {
	return constraint.ComplementMacroConstraint(mainExpr)
}

// IsGenFile reports whether path is a generated macro file.
func IsGenFile(path string) bool {
	return strings.HasSuffix(path, genSuffix)
}

// IsMacroMainFile reports whether file has macro build tag.
func IsMacroMainFile(src string) bool {
	expr, ok := constraint.ExtractBuildConstraint(src)
	if !ok {
		return false
	}
	has, _ := constraint.HasMacro(expr)
	return has
}
