// Code generated by go-macro; DO NOT EDIT.

//go:build !macro

package readfile

import (
	"fmt"
	"os"
)

func ReadFile() (bs []byte, err error) {
//line readfile.go:16
	defer func() {
		if err != nil {
			err = fmt.Errorf("readfile: %w", err)
		}
	}()
//line readfile.go:21
	_v2, _err1 := os.Open("hello.txt")
//line readfile.go:21
	if _err1 != nil {
		return nil, _err1
	}
//line readfile.go:21
	file := _v2
//line readfile.go:22
	defer file.Close()
//line readfile.go:23
	return os.ReadFile("hello.txt")
}
